name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger on tags like v1.0.0

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'

    - name: Publish Application
      run: dotnet publish -c Release -r win-x64 --self-contained -p:PublishSingleFile=true -o publish/

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ github.ref_name }}
        name: ${{ github.ref_name }}
        artifacts: publish/*
        token: ${{ secrets.GITHUB_TOKEN }}

